### ISSUE TITLE
메인 화면을 구성한다

### ISSUE THREAD

**Issue by hwookim** [3D-Script-Programming/DungeonAgency#15]
대략적인 도안

![스크린샷 2021-06-11 오후 6 22 05](https://user-images.githubusercontent.com/45786387/121664039-062d8c00-cae2-11eb-9a6a-0805520b3589.png)

최종 기획서 내에 있는 이거 참고함
![스크린샷 2021-06-11 오후 11 36 00](https://user-images.githubusercontent.com/45786387/121703451-ce3c3e00-cb0d-11eb-9c49-9c4995978381.png)

**Comment by GyeongyeonAn** [comment]
배치도 좋은데요!? 기대가 됩니다.
